config/routes.rb
ShaneBlog::Application.routes.draw do
  devise_for :admin, only: ["sessions"]

  root :to => "articles#index"
  resources :articles, except: ["index"]
  match "articles_archive", to: "articles#list"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :tag

  validates :body, :title, :tag, presence: true
  validates :body, :title, uniqueness: true
  validate :check_tag

  def self.tags
    [
      "Startups",
      "Projects",
      "Articles",
      "AboutMe"
    ]

  end

  private
    def check_tag
      Article.tags.each{|t| return if tag.include?(t)}
      errors.add(:tag, "Not a valid tag!")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :latest_articles
  before_filter :init_parser
  before_filter :init_tag

  def latest_articles
    @latest = Article.order("created_at DESC").take(10)
  end

  def init_parser
    @parser = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end

  def init_tag
    @tag = valid_tag?(params[:tag]) ? params[:tag] : "Articles"
  end

  def tags
   Article.tags
  end

  def valid_tag? tag
    tags.each{|t| return true if tag == t}
    false
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :check_admin

  # GET /articles/
  # GET /articles/.json
  def index
    if @tag != "Articles"
      @articles = Article.where("title like ?", "%#{params[:search]}%").where("tag like ?", "#{@tag}%").order("created_at DESC").paginate page: params[:page]
    else
      @articles = Article.where("title like ?", "%#{params[:search]}%").order("created_at DESC").paginate page: params[:page]
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/list
  # GET /articles/list.json
  def list
    if @tag != "Articles"
      @articles = Article.where("title like ?", "%#{params[:search]}%").where("tag like ?", "#{@tag}%").order("created_at DESC").paginate page: params[:page]
    else
      @articles = Article.where("title like ?", "%#{params[:search]}%").order("created_at DESC").paginate page: params[:page]
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/create
  # GET /articles/create.json
  def create
    @article = Article.new params[:article]
    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /jobs/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to article_path(@article), notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private

    def check_admin
      return if action_name == "index" || action_name == "list" || action_name == "show"
      redirect_to "/404.html" unless admin_signed_in?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  def gravatar_url
    hash = Digest::MD5.hexdigest("shaneburkhart@gmail.com")
    "http://www.gravatar.com/avatar/#{hash}?s=200&d=mm"
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
  = f.input :title, input_html: { class: "span8", id: "article-title" }
  = f.input :tag, input_html: { class: "span5", id: "article-tag" }
  = f.input :body, input_html: { class: "span8", id: "article-body" }
  = f.submit
  - if !@article.id.nil?
    = link_to 'Delete',
        article_path(@article),
        :method => :delete,
        :confirm => 'Are you sure you wish to delete this listing?',
        :class => 'btn btn-danger'

  =link_to "Markdown Helper", "http://daringfireball.net/projects/markdown/basics"

%hr

%h1#title-preview
%p.lead#tag-preview= @article.tag
%hr
#body-preview

app/views/articles/edit.html.haml
= render "form"

app/views/articles/index.html.haml
%h1= @tag
= form_tag root_path, method: :get, class: "form-inline search-form" do
  = hidden_field_tag :tag, params[:tag]
  = text_field_tag :search, params[:search], class: "input-large", placeholder: "Search Articles"
  = submit_tag "Search", class: "btn btn-primary", name: nil
= will_paginate @articles, renderer: BootstrapPagination::Rails
%hr
- @articles.take(15).each do |article|
  %h2= link_to article.title, article_path(article)
  %p.lead.muted= article.tag
  %p.muted
    = distance_of_time_in_words Time.now, article.created_at
    ago
  .row-fluid
    .span12
      = @parser.render(article.body).html_safe
  %hr
= will_paginate @articles, renderer: BootstrapPagination::Rails

app/views/articles/list.html.haml
%h1
  = @tag
  Archives
= form_tag articles_archive_path, method: :get, class: "form-inline search-form" do
  = hidden_field_tag :tag, params[:tag]
  = text_field_tag :search, params[:search], class: "input-large", placeholder: "Search Articles"
  = submit_tag "Search", class: "btn btn-primary", name: nil
= link_to "Back", root_path
= will_paginate @articles, renderer: BootstrapPagination::Rails
%hr
- @articles.each do |article|
  %h4= link_to article.title, article_path(article)
= will_paginate @articles, renderer: BootstrapPagination::Rails

app/views/articles/new.html.haml
= render "form"

app/views/articles/show.html.haml
%h1= @article.title
%p.lead.muted= @article.tag
%p.muted
  = distance_of_time_in_words Time.now, @article.created_at
  ago
- if admin_signed_in?
  = link_to "Edit Article", edit_article_path(@article), class: "btn"
- else
  = link_to "Back", root_path

%hr
.row-fluid
  .span12
    = @parser.render(@article.body).html_safe

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Shane Burkhart", root_path, :class => 'brand'
%ul.nav.pull-right
  %li
    = link_to "Articles", root_path
  %li
    = link_to "Projects", root_path + "?tag=Projects"
  %li
    = link_to "Startups", root_path + "?tag=Startups"
  %li
    = link_to "Github", "https://github.com/ShaneBurkhart"
  %li
    = link_to "Twitter", "https://twitter.com/DonkkaShane"
  %li
    = link_to "About Me", root_path + "?tag=AboutMe"

app/views/layouts/_sidenav.html.haml
.text-center
  = image_tag gravatar_url, class: "gravatar"
- if admin_signed_in?
  %h4 Dashboard
  %ul.nav.nav-tabs.nav-stacked
    %li= link_to "New Article", new_article_path
%h4 Recent Articles
%ul.nav.nav-tabs.nav-stacked
  - @latest.each do |article|
    %li= link_to article.title, article_path(article)
%h4 Archives
%ul.nav.nav-tabs.nav-stacked
  %li= link_to "Browse All Articles", articles_archive_path + "?tag=#{@tag}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    - if Rails.env.production?
      = javascript_include_tag "googleanalytics"
    %title= content_for?(:title) ? yield(:title) : "Shane Burkhart"
    %meta{:content => content_for?(:description) ? yield(:description) : "Shane Burkhart", :name => "description"}
      = stylesheet_link_tag "application", :media => "all"
      = javascript_include_tag "application"
      = csrf_meta_tags
      = yield(:head)

  %body{data: { controller: controller_name, action: action_name }}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .span3
            = render "layouts/sidenav"
          .span9
            = render 'layouts/messages'
            = yield
        %footer
      / ! end of .container
    / ! end of #main